banner:
  location: classpath:banner.txt
liquibase:
  enabled: true
spring:
  batch:
    initializer:
      enabled:    true
    job:
      enabled:    false
  datasource:
    driver-class-name: org.postgresql.Driver
    url:               jdbc:postgresql://localhost:5432/sample
    username:          sample
    password:          sample
  jpa:
    show-sql:          true
    hibernate:
      ddl-auto:        none
    properties:
      hibernate:
        format_sql:    true
        hbm2ddl:
          auto:        validate
        jdbc:
          batch_size:  10
        order_inserts: true
        order_updates: true
batch:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:               jdbc:postgresql://localhost:5432/tech
    username:          sample
    password:          sample
first:
  chunck:
    size: 10
